### ISSUE TITLE
enableMetricData?

### ISSUE THREAD

**Issue by dudicoco** [sysdiglabs/promcat-resources#74]
Hi,

In some of the configuration example the parameter `enableMetricData` is specified.
I could not find this parameter in the YACE repo, is it a mistake?

**Comment by daviddetorres** [comment]
Hi. 

This parameter appeared for first time in February when the GetMetricsData function was implemented and was used when both GetMetricsData and GetMetricStatistics were both used in the exporter. Later the GetMetricStatistics call was removed and this parameter was no longer used.

We keep on using it to offer back compatibility with the previous versions that were using two versions of the API call, but at some point, we will  update the configurations files to remove it and also update the config files with the newer versions of the YACE exporter (for example, to support multiple regions).

Thanks for the comment! :cat:

**Comment by dudicoco** [comment]
@daviddetorres thank you, I assumed that it might be a deprecated parameter :)

Could you also explain why `period: 300` and `length: 3600` were chosen for https://promcat.io/apps/aws-alb?
ALB supports 60 seconds granularity, so something like `period: 60` and `length: 180` would give more accurate results.
Honestly i'm still not sure on what are the pros and cons of setting length high/low. I would assume setting it low would result in faster fetching of the metrics, so length should be set as low as possible as long as the pervious scrape results overlap with the new scrape results?

**Comment by daviddetorres** [comment]
Hi! 

In PromCat we adopted a compromise between a scraping interval short enough to have reliable data and not too frequent to optimize the ClouWatch bill. 

As you noted, you can choose a period of 60 seconds, but this affects the CloudWatch billing in 2 ways: 
* The number of 60 seconds metrics that you use
* The number of API requests that you have to do

Also the [YACE exporter](https://github.com/ivx/yet-another-cloudwatch-exporter) uses mirroring to collect data every 5 minutes and not every time you visit /metrics. To change the scraping interval to 60s, you have to pass the following argument:
```
--scraping-interval=60 
```

About the length, it is a conservative value due to CloudWatch can take some time to produce the data and it is not always available just after being produced. If you adjust the length too much it can produce gaps in the data.

**Comment by dudicoco** [comment]
Thanks @daviddetorres!

I am already using `--scraping-interval=60 ` :)

Since I want to alert on the alb metrics I chose a period of 60 seconds and a 60 seconds scraping interval.

I am aware of the delay in the data that CloudWatch api calls produce (around 2 minutes), therefor i'm thinking a length of 180 would be sufficient to cover the gap, I could also use a length of 300 to be on the safe side but would that cause longer scrape time and/or higher costs?

**Comment by daviddetorres** [comment]
If you want it for alerting, I recommend a 300 length at least to ensure that there is no gap in the data. 

The scraping time would not be affected by that. I'm not sure about the billing, but passing from 180 to 300 should not be critical. 

As this is configurable by metric you can set it up to 300 in the most critical ones and leave the others to 180.

**Comment by dudicoco** [comment]
@daviddetorres thank you, very helpful information!

**Comment by daviddetorres** [comment]
#84
This removes the field `enableMetricData` from the configurations and updates the image of the exporter.
